kind: Service
apiVersion: v1
metadata:
  name: dask-scheduler
spec:
  selector:
    app: dask-scheduler
  ports:
  - name: dask-scheduler
    port: 8786
    targetPort: 8786
  - name: dask-ui
    port: 8787
    targetPort: 8787

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dask-scheduler
  name: dask-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dask-scheduler
    spec:
      containers:
      - args:
        - dask-scheduler
        image: quanted/vb_dask:latest
        name: dask-scheduler
        ports:
        - containerPort: 8786
        - containerPort: 8787
      hostname: dask-scheduler
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dask-worker
  name: dask-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dask-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dask-worker
    spec:
      hostname: dask-worker
      restartPolicy: Always
      containers:
      - name: dask-worker
        command:
        - dask-worker
        - dask-scheduler:8786
        image: quanted/vb_dask:latest
        env:
          - name: IN_DOCKER
            value: "True"
          - name: DASK_SCHEDULER
            value: "dask-scheduler:8786"
        volumeMounts:
          - mountPath: /app
            name: vb-dask-volume
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "4Gi"
      volumes:
        - name: vb-dask-volume
          hostPath:
            path: /host/vb_django
#            type: Directory

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dask-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dask-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75

