apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vb-django
  name: vb-django
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
       app: vb-django
  template:
    metadata:
      labels:
        app: vb-django
    spec:
      hostname: vb-django
      containers:
      - name: vb-django
        image: dbsmith88/vb_django:latest
        command:
          - sh
          - /opt/app/vb_django/start-server.sh
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: vb-config
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /opt/app/vb_django
          name: vb-django-volume
        - mountPath: /opt/app/collected-static
          name: vb-collected-static
      restartPolicy: Always
      volumes:
      - name: vb-django-volume
        hostPath:
#          path: /host/vb_django
          path: /D//git/vb/vb_kube/vb_django
      - name: vb-collected-static
        persistentVolumeClaim:
          claimName: vb-collected-static-pvc
