apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: daskKubernetes
  namespace: default
rules:
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"
- apiGroups:
  - ""  # indicates the core API group
  resources:
  - "pods/log"
  - "services"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "delete"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dask-kube-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: daskKubernetes
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: dask-kube

---

apiVersion: v1
kind: ServiceAccount
metadata:
 name: dask-kube
 namespace: default
