apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vb-dask-worker
  namespace: qed-kube-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vb-dask-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 150
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90