# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: vb-nginx-certs-pvc
#   namespace: qed-kube-dev
#   labels:
#     app: vb-nginx-certs
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   selector:
#     matchLabels:
#       release: "stable"
#       name: vb-nginx-certs-pv

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: vb-collected-static-pvc
#   namespace: qed-kube-dev
#   labels:
#     app: vb-collected-static
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi
#   selector:
#     matchLabels:
#       release: "stable"
#       name: vb-collected-static-pv