apiVersion: v1
kind: ConfigMap
metadata:
  name: vb-postgres-config
  labels:
    app: vb-postgres
data:
  POSTGRES_DB: vb_postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vb-postgres-pv
  labels:
    type: local
    app: vb-postgres
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /host/app_data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vb-postgres-pv-claim
  labels:
    app: vb-postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      release: "stable"
      name: vb-postgres-pv

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: vb-vb-postgres
  ports:
  - protocol:
    port: 5432
    targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vb-postgres
  name: vb-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vb-postgres
  serviceName: vb-postgres
  template:
    metadata:
      labels:
        app: vb-postgres
    spec:
      containers:
      - image: postgres
        name: vb-postgres
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: vb-postgres-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: vb-postgres-pvolume
      terminationGracePeriodSeconds: 10
      volumes:
      - name: vb-postgres-pvolume
        persistentVolumeClaim:
          claimName: vb-postgres-pv-claim