# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: vb-postgres-pv-claim
#   namespace: qed-kube-dev
#   labels:
#     app: vb-postgres
# spec:
#   accessModes:
#     - ReadWriteMany
#   # storageClassName: efs-sc
#   resources:
#     requests:
#       storage: 5Gi
#   selector:
#     matchLabels:
#       release: "stable"
#       name: "vb-postgres-pv"
